# fly.toml file generated for marketwatcher on 2023-04-27T13:59:50-05:00

app = "marketwatcher"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "den"
processes = []

[env]
  PORT = "8080"
  PRIMARY_REGION = "den"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = []
  entrypoint = []
  exec = []

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
